[versions]
simbot = "4.0.0-dev2"

[libraries]
simbot-api = { group = "love.forte.simbot", name = "simbot-api", version.ref = "simbot" }
simbot-core = { group = "love.forte.simbot", name = "simbot-core", version.ref = "simbot" }
